#!/bin/bash
# Install the repo's git hooks. Run once after cloning:  ./scripts/install-hooks.sh
#
#   pre-push           — the shared-queue guard: refuses to ship other lanes'
#                        commits, names the blocking run and its owner. It was
#                        GENERATED by the python server, which was deleted at
#                        792ce1f — so nothing regenerated it and it survived as
#                        an orphan in ONE checkout (AMUX-2940).
#   prepare-commit-msg — stamps Amux-Session on every commit, `(human)` when
#                        there is no session (AMUX-2567). Until 2026-08-11 this
#                        hook was NOT installed by this script: it existed as a
#                        hand-placed file in one checkout and nowhere else, so a
#                        fresh clone produced untrailered commits that the push
#                        guard must read as foreign.
#   pre-commit         — secret scan + Rust/client-JS syntax, and the shim that
#                        calls the staged-guard below
#   amux-staged-guard  — cross-session sweep protection (AMUX-1730)
#
# WHY THIS NOW INSTALLS TWO FILES (2026-08-09). It used to install only
# pre-commit, on the grounds that amux-staged-guard was a GENERATED artifact:
# the Python server wrote it per work_dir and injected its own shim. That was
# right while python ran. amux-server.py is now deleted and nothing in the rust
# server generates the hook, so the "the server will install it" advice this
# script printed was false, and — worse — overwriting pre-commit here DELETED
# the shim the retired python had injected, turning the guard off while
# printing "ok ... matches".
#
# So the tracked copies are now the ONLY producer. If a generator ever comes
# back, remove them here in the same commit that adds it (the 2026-08-06 revert
# explains what a second producer costs).
#
# USAGE
#   ./scripts/install-hooks.sh                 # this repo (both files)
#   ./scripts/install-hooks.sh /path/to/repo   # ANOTHER checkout: guard only
#   ./scripts/install-hooks.sh --all           # every checkout that already has it
#
# WHY THE OTHER-CHECKOUT MODE EXISTS (2026-08-10). The guard is installed in
# nine checkouts on this machine; eight of them are not amux and have their own
# `pre-commit` (a repo-specific hook with the amux shim injected at the top).
# Only ONE of the nine was reachable by this script, because it resolved
# `$ROOT` from the CURRENT repo and then read `$ROOT/scripts/git-hooks/` —
# which exists nowhere but amux. So after the python generator was deleted,
# every non-amux checkout was frozen on whatever the generator last wrote and
# nothing could update it: eight stale guards, all still addressing the retired
# port, with no supported way to fix them. Sources come from the AMUX checkout
# (where this script lives) and the TARGET is an argument.
#
# The foreign mode NEVER writes `pre-commit`. Those files are the other repo's,
# they carry that repo's own checks (jekyll builds, `pre-commit run`, secret
# scans), and amux's tracked pre-commit runs Rust/client-JS checks that are
# meaningless there. Overwriting one would destroy a user's hook as a side
# effect of a refactor (ethos rule 8) — and it is exactly the mistake this
# script already made once, in the other direction, by overwriting amux's
# pre-commit and silently deleting the shim. It reports instead.
set -e
# Sources always come from the amux checkout this script lives in, never from
# the target — that is the whole bug the foreign mode fixes.
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --- foreign checkout: install the guard, verify, never touch their pre-commit
# THE TRACKED MODE IS PART OF THE PROTECTION (AMUX-2663). install here uses
# -m 0755 and so masks a wrong mode at the source — which is exactly how the
# guard sat tracked as 100644 while every checkout that ran this script looked
# fine. Any checkout that did NOT run it (a fresh clone, cp -p, tar) got a
# non-executable guard, `[ -x ]` in pre-commit failed, and cross-session sweep
# protection was silently OFF. Assert the source mode so it cannot regress
# behind this script's own success.
check_tracked_guard_mode() {
  local mode
  mode=$(git -C "$SRC" ls-files -s scripts/git-hooks/amux-staged-guard 2>/dev/null | awk '{print $1}')
  if [ "$mode" != "100755" ]; then
    echo "  FAIL scripts/git-hooks/amux-staged-guard is tracked as ${mode:-<untracked>}, not 100755." >&2
    echo "       Every checkout that does not run this script gets a NON-EXECUTABLE guard," >&2
    echo "       pre-commit's [ -x ] test fails, and sweep protection is off with one line" >&2
    echo "       on stderr. Fix: git update-index --chmod=+x scripts/git-hooks/amux-staged-guard" >&2
    return 1
  fi
  echo "  ok   scripts/git-hooks/amux-staged-guard is tracked executable (100755)"
  return 0
}

install_guard_only() {
  local target="$1" fail=0
  if [ ! -d "$target/.git/hooks" ]; then
    echo "  SKIP $target — no .git/hooks (not a checkout, or a linked worktree)" >&2
    return 0
  fi
  install -m 0755 "$SRC/scripts/git-hooks/amux-staged-guard" "$target/.git/hooks/amux-staged-guard"
  if cmp -s "$SRC/scripts/git-hooks/amux-staged-guard" "$target/.git/hooks/amux-staged-guard"; then
    echo "  ok   $target/.git/hooks/amux-staged-guard matches the tracked source"
  else
    echo "  FAIL $target/.git/hooks/amux-staged-guard differs after install" >&2
    fail=1
  fi
  # THE SESSION STAMP (AMUX-2567). Installed alongside the guard because the
  # guard's attribution is only as good as the trailer: with no
  # prepare-commit-msg, every commit in this checkout is untrailered, the push
  # recipe in CLAUDE.md says to "treat as foreign", and a peer's ordinary work
  # is indistinguishable from a hook-bypassing graft.
  #
  # It was NOT installed by this script before — it existed as a hand-placed
  # file in one checkout's .git/hooks and nowhere else, so a fresh clone got
  # silent non-attribution and looked fine. Unlike pre-commit (which we refuse
  # to rewrite, because it is the repo owner's), prepare-commit-msg is entirely
  # ours: nothing else claims it, so installing it is safe.
  install -m 0755 "$SRC/scripts/git-hooks/prepare-commit-msg" "$target/.git/hooks/prepare-commit-msg"
  if cmp -s "$SRC/scripts/git-hooks/prepare-commit-msg" "$target/.git/hooks/prepare-commit-msg"; then
    echo "  ok   $target/.git/hooks/prepare-commit-msg matches the tracked source"
  else
    echo "  FAIL $target/.git/hooks/prepare-commit-msg differs after install" >&2
    fail=1
  fi
  # The shim is the whole chain: an installed guard nothing calls is a file, not
  # a guard. We do not write their pre-commit, so all we can do is check it and
  # hand over the exact lines — which is the honest move, not a silent no-op.
  local pc="$target/.git/hooks/pre-commit"
  if [ -f "$pc" ] && grep -q 'amux-staged-guard' "$pc" && grep -q '"\$g" || exit 1' "$pc"; then
    echo "  ok   $target pre-commit calls amux-staged-guard"
  else
    echo "  WARN $target pre-commit does NOT call amux-staged-guard — sweep protection is OFF there." >&2
    echo "       This script will not edit another repo's pre-commit. Add these 3 lines near the top:" >&2
    echo '         g="$(dirname -- "$0")/amux-staged-guard"' >&2
    echo '         if [ -x "$g" ]; then "$g" || exit 1; fi' >&2
    fail=1
  fi
  return $fail
}

if [ "${1:-}" = "--all" ]; then
  # Bounded scan, and it PRINTS its bounds: a discovery step that silently
  # missed a checkout would report "all clear" over an unpatched hook, which is
  # the same class of false-green as a grep that could not have matched.
  roots="${AMUX_HOOK_SCAN_ROOTS:-$HOME/Dev}"
  echo "scanning for installed amux guards under: $roots (override: AMUX_HOOK_SCAN_ROOTS)"
  check_tracked_guard_mode || true
  allfail=0
  found=0
  # shellcheck disable=SC2086
  while IFS= read -r g; do
    repo="${g%/.git/hooks/amux-staged-guard}"
    found=$((found + 1))
    if [ "$repo" = "$SRC" ]; then continue; fi   # self is handled below
    install_guard_only "$repo" || allfail=1
  done < <(find $roots -maxdepth 6 -type f -path '*/.git/hooks/amux-staged-guard' -not -path '*/node_modules/*' 2>/dev/null | sort)
  echo "  ($found checkouts had the guard installed)"
  [ "$allfail" -eq 0 ] || echo "one or more checkouts need attention (see WARN/FAIL above)" >&2
  # fall through to install into the amux checkout itself
elif [ -n "${1:-}" ]; then
  check_tracked_guard_mode || true
  install_guard_only "$(cd "$1" && pwd)"
  exit $?
fi
check_tracked_guard_mode || true

ROOT="$SRC"

install -m 0755 "$ROOT/scripts/git-hooks/pre-commit" "$ROOT/.git/hooks/pre-commit"
install -m 0755 "$ROOT/scripts/git-hooks/amux-staged-guard" "$ROOT/.git/hooks/amux-staged-guard"
install -m 0755 "$ROOT/scripts/git-hooks/prepare-commit-msg" "$ROOT/.git/hooks/prepare-commit-msg"
install -m 0755 "$ROOT/scripts/git-hooks/pre-push" "$ROOT/.git/hooks/pre-push"
install -m 0755 "$ROOT/scripts/git-hooks/post-commit" "$ROOT/.git/hooks/post-commit"

# Verify rather than announce (ethos #7): compare what landed against its source,
# so a stale installed copy cannot hide behind a success message. That drift was
# real and security-relevant — the AC-239 secret patterns (Clerk, R2, Slack,
# GitLab) sat in the tracked hook while .git/hooks/pre-commit was months old, so
# commits printed "Security scan passed" from a scanner that could match none of
# them.
fail=0
for h in pre-commit amux-staged-guard prepare-commit-msg pre-push post-commit; do
  if cmp -s "$ROOT/scripts/git-hooks/$h" "$ROOT/.git/hooks/$h"; then
    echo "  ok   .git/hooks/$h matches scripts/git-hooks/$h"
  else
    echo "  FAIL .git/hooks/$h differs from scripts/git-hooks/$h" >&2
    fail=1
  fi
done

# The shim is the whole chain: an installed guard that pre-commit never calls is
# a file, not a guard. Check the LINK, not just the two files — this is exactly
# the failure that shipped when pre-commit was overwritten without it.
if grep -q 'amux-staged-guard' "$ROOT/.git/hooks/pre-commit" \
   && grep -q '"\$g" || exit 1' "$ROOT/.git/hooks/pre-commit"; then
  echo "  ok   pre-commit calls amux-staged-guard"
else
  echo "  FAIL pre-commit does NOT call amux-staged-guard — sweep protection is OFF" >&2
  fail=1
fi

# And the guard is only a guard if the SERVER routes its endpoint. Unrouted, it
# fails open and (before 2026-08-09) said nothing: POST /api/git/staged-guard
# answered 405 for the whole rust cutover, ~1,147 calls an hour, every one
# swallowed. Report it here, where someone is already looking at hooks.
#
# The base URL comes from the guard's OWN resolver, imported rather than
# re-spelled: it self-heals a stale inherited `AMUX_URL` (see the docstring on
# `amux_base_url`). Checking a different address than the guard will use would
# make this line report on a server the guard never talks to.
BASE="$(python3 -c "
import importlib.machinery, sys
m = importlib.machinery.SourceFileLoader('amux_guard', '$ROOT/scripts/git-hooks/amux-staged-guard').load_module()
print(m.amux_base_url())" 2>/dev/null)" || BASE=""
[ -n "$BASE" ] || BASE="${AMUX_URL:-https://localhost:8824}"
URL="$BASE/api/git/staged-guard"
code=$(curl -sk -o /dev/null -w '%{http_code}' -m 3 -X POST \
        -H 'Content-Type: application/json' -d '{}' "$URL" 2>/dev/null || echo 000)
case "$code" in
  400|200) echo "  ok   server routes POST /api/git/staged-guard (HTTP $code)" ;;
  000)     echo "  note amux server not reachable at $URL — could not check the endpoint" ;;
  404|405|501)
    # Loud, but NOT `fail=1`: the installer's exit code is a verdict on what it
    # installed, and a stale server is not something it can fix. The guard
    # itself now prints this on every commit, which is the enforcement point.
    echo "  WARN server does NOT route POST /api/git/staged-guard (HTTP $code) —" >&2
    echo "       the guard fails open on every commit until the amux server is updated." >&2 ;;
  *)       echo "  note POST /api/git/staged-guard answered HTTP $code" ;;
esac

[ "$fail" -eq 0 ] || exit 1
echo "hooks installed: secret scan + Rust/client-JS syntax + cross-session staged-guard."
